### ISSUE TITLE
Error when creating new user after docker installation

### ISSUE THREAD

**Issue by SmartPhoneLover** [KlausSchaefers/quant-ux#251]
I used the klausschaefers docker-compose file to build the stack, for testing.

After creating all the containers, up and running, I go to the main page, and click on Sign UP. But, a message telling to me that the password is stoo short is shown, whatever password I type:
![9348573489565646](https://github.com/KlausSchaefers/quant-ux/assets/42898749/1a854bb1-4004-4694-8e06-203d67ce78d6)

I have tried with text strings from 10 to 30 chars.

This is the Docker Compose I have:

```
services:

  frontend:
    image: klausenschaefersinho/quant-ux:latest
    container_name: quantux-frontend
    ports:
      - "10010:8082/tcp"
    environment:
      - QUX_PROXY_URL=http://quantux-backend:8080
      - QUX_AUTH=qux
      - QUX_KEYCLOAK_REALM=
      - QUX_KEYCLOAK_CLIENT=
      - QUX_KEYCLOAK_URL=
      - QUX_WS_URL=ws://127.0.0.1:8086
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - quantux-net

  backend:
    image: klausenschaefersinho/quant-ux-backend:latest
    container_name: quantux-backend
    environment:
      - QUX_HTTP_HOST=http://quantux-frontend:8082
      - QUX_HTTP_PORT=8080
      - QUX_MONGO_DB_NAME=quantux
      - QUX_MONGO_TABLE_PREFIX=quantux
      - QUX_MONGO_CONNECTION_STRING=mongodb://database:27017
      # QUX_MAIL_USER=<mail_user>
      # QUX_MAIL_PASSWORD=<mail_pass>
      # QUX_MAIL_HOST=<mail_domain>
      - QUX_JWT_PASSWORD=ntxy5hZ8N4tm6iVn6zySKscGYoK437
      - QUX_IMAGE_FOLDER_USER=/app-data/qux-images
      - QUX_IMAGE_FOLDER_APPS=/app-data/qux-image-apps
      - QUX_AUTH_SERVICE=qux
      - QUX_KEYCLOAK_SERVER=
      - QUX_KEYCLOAK_REALM=
      - QUX_USER_ALLOW_SIGNUP=true
      - QUX_USER_ALLOWED_DOMAINS=*
      - TZ=Europe/Madrid
    volumes:
      - /home/debian/docker-data/quant-ux/data:/app-data
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - quantux-net

  websocket:
    image: klausenschaefersinho/quant-ux-websocket:latest
    container_name: quantux-websocket
    ports:
      - "10011:8086/tcp"
    environment:
      - QUX_SERVER=http://quantux-backend:8080/
      - QUX_SERVER_PORT=8086
    restart: unless-stopped
    networks:
      - quantux-net

  database:
    image: mongo:4.4.22
    container_name: quantux-db
    environment:
      - MONGO_INITDB_DATABASE=quantux
      - MONGO_INITDB_ROOT_USERNAME=quantux
      - MONGO_INITDB_ROOT_PASSWORD=quantux
    volumes:
      - /home/debian/docker-data/quant-ux/mongodb:/data/db
    restart: always
    networks:
      - quantux-net

networks:
  quantux-net:
    name: quantux-net
```

Also, I would like to ask another question...
Is the websocket required actually to run the full stack, if I'm not going to configure the service to be exposed (reverse-proxy)?

Thank you!
