### ISSUE TITLE
Not able to login after sign-up

### ISSUE THREAD

**Issue by asitemade4u** [KlausSchaefers/quant-ux#72]
Hi @KlausSchaefers , I am following [Awesome OpenSource tutorial on YouTube](https://www.youtube.com/watch?v=liL0FyQOG-k) and was able to deploy Quant UX with no difficulty.
Where I have a problem is when trying to **sign-in after I have signed up**. 
I signed up twice, once from the local docker stack, once from the Quant UX website and I could not login when trying to from the docker installation.
The symptom is that the **Login** button is not responsive.
Our intranet is in a very secure environment with a firewall: it is going through a VPN and the exterior is not able to access the intranet.
If that is the reason, what ingress port should I open to allow login?

**Comment by KlausSchaefers** [comment]
Hi,

you are using the docker compose file from https://github.com/bmcgonag/quant-ux-docker/, correct?

All communication happens over HTTP / REST, so it should be fine with Firewalls.

Can you open open the developer console in Chrome to check the network traffic? Ist there some issue?

Thanks,

Klaus

**Comment by asitemade4u** [comment]
Hi Klaus, thanks for your prompt response.

- Yes, I am using the stack you mentioned.
- I am using Firefox and here is the outcome in the developer console of me clicking on the Login button, once my email and passwords were input:

```
Error: Could not post
    value AbstractService.js:139
    promise callback*value/< AbstractService.js:125
    value AbstractService.js:119
    e UserService.js:29
    f runtime.js:63
    r runtime.js:294
    x runtime.js:119
    Babel 4
    t app.01125b1a.js:1
    e LoginPage.vue:76
    f runtime.js:63
    r runtime.js:294
    x runtime.js:119
    Babel 4
    login LoginPage.vue:74
    VueJS 3
vue.runtime.esm.js:1897:12
```

**Comment by asitemade4u** [comment]
Just FYI, I am usinf Firefox 98.0 (last stable version) on Debian 11.

**Comment by KlausSchaefers** [comment]
Could you try Chrome?

**Comment by asitemade4u** [comment]
Yup. Is BRAVE (which is based upon Chrome) a good alternative for you -- 
I am not too fond of Google snooping into my stuff ;o))

**Comment by asitemade4u** [comment]
OK, I tried with Brave (which is based upon Chrome) and it does the same:

I attach the log.

**Comment by KlausSchaefers** [comment]
I am not seeing the log...

**Comment by asitemade4u** [comment]
Here you go (did not go through when sent by email)
[i85.qtpl.net-1647207420739.log](https://github.com/KlausSchaefers/quant-ux/files/8240660/i85.qtpl.net-1647207420739.log)
[i85.qtpl.net-1647207426982.log](https://github.com/KlausSchaefers/quant-ux/files/8240661/i85.qtpl.net-1647207426982.log)
.

**Comment by KlausSchaefers** [comment]
Puh, this is a hard one. I just tried the docker compose and here everything works. 

1) Do you see anything strange in the docker console?

2) Do you have any firewalls or so installed? It should don't matter if you can open the UI though...

3) You have any add-blocker installed?

4) If the developer tools, can you take a look at the network traffic? When you sign-in there should be a request to "/rest/user" going though with some JSON response. The next request to "rest/login/" seems to give an error.

**Comment by asitemade4u** [comment]
Here are my answers:

 1. You are right, there WAS indeed something wrong in the docker
    console of the main component:
    `21:56:45.253 [vert.x-worker-thread-6] ERROR com.qux.bus.VMHeater -
    touchMongo() > error`
    But I do not understand why because the Mongo container works fine
    and nothing wrong appears in its console
 2. Yes, I am using OPNsense but I have opened all ports needed by Quant UX
 3. Yes, I am using strong browser extensions against attacks but I
    tried to connect using the Private Browsing mode (where extensions
    are disabled) and it does the same

**Comment by asitemade4u** [comment]
As per #4, here is a screen copy of the Network debugging:
![image](https://user-images.githubusercontent.com/11460106/158081174-81b8ad0f-89c9-4671-a87a-c93e004727af.png)

**Comment by KlausSchaefers** [comment]
Hi,

could you try another docker image in the compose file?

```
version: '3'

services:
 ...
  qux-fe:
    restart: always
    container_name: quant-ux-frontend
    image: klausenschaefersinho/quant-ux
    ....
  qux-be:
    restart: always
    container_name: quant-ux-backend
    image: klausenschaefersinho/quant-ux-backend
   ....

```

**Comment by KlausSchaefers** [comment]
Can you somehow open the server for me, so I can try to access it over the web?

**Comment by asitemade4u** [comment]
Nope, this one is difficult as we are operating in a secure environment 
+ have been attacked recently.
Sorry.

**Comment by asitemade4u** [comment]
Hi Klaus,

Sorry for the belated response.
I just tried and it does the same.

**Comment by KlausSchaefers** [comment]
Hi,

also when you run the docker compose locally?

**Comment by asitemade4u** [comment]
So:

1. I tried the exact same docker-compose file on my local machine and it had the exact same outcome
2. I attach the `docker-compose.yml` file (I changed the extension to `txt` as GH does not allow `yml` files)
3. Also, could you verify my credentials o
[qux.txt](https://github.com/KlausSchaefers/quant-ux/files/8247805/qux.txt)
n your access database? Maybe you could reset my password in case it might have failed. The email I used is `stephen@asitemade4u.com`

**Comment by asitemade4u** [comment]
I just also tried from a Firefox in Private mode (no extension loaded) and it did the same with the local deployment

**Comment by asitemade4u** [comment]
Lastly, I tried with a `localhost:port` address from my machine and it did the same.

**Comment by KlausSchaefers** [comment]
Hi,

your account should not be in my database. The docker compose spins up it's own backend and frontend.

**Comment by KlausSchaefers** [comment]
It looks to me, like the docker-compose was missing the container name, so the HTTP request could not be resolved. Can you try this?

```
version: "3"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: qux-mgo
    volumes:
      - /home/stsinc/dkr/qux/mgo:/data/db
    labels:
      - com.centurylinklabs.watchtower.enable=true

  qux-fe:
    image: klausenschaefersinho/quant-ux
    restart: unless-stopped
    container_name: qux-frt
    environment:
      - QUX_PROXY_URL=http://quant-ux-backend:8080
    links:
      - mongo
      - qux-be
    ports:
      - 8082:8082
    depends_on:
      - qux-be
    labels:
      - com.centurylinklabs.watchtower.enable=true

  qux-be:
    container_name: quant-ux-backend # I added this
    image: klausenschaefersinho/quant-ux-backend
    restart: unless-stopped
    container_name: qux
    environment:
      # - QUX_MAIL_PASSWORD=sTr0ngPa55w0Rd
      - QUX_HTTP_HOST=http://quant-ux-frontend:8082
      - QUX_HTTP_PORT=8080
      - QUX_IMAGE_FOLDER_APPS=/qux-image-apps
      - QUX_IMAGE_FOLDER_USER=/qux-images
      - QUX_JWT_PASSWORD="eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJzdGVwaGVuQG91cnF1aWV0cGxhY2VzLmNvbSIsIlVzZXJuYW1lIjoia3VxIiwiZXhwIjoxNjQ3MDk4MzU3LCJpYXQiOjE2NDcwOTgzNTd9.-q7lI5FA63Y3fH4WSIrDZTM1fiWU-uFDBaBs7hsYbjo"
      - QUX_MAIL_HOST=10.0.10.75:1025
      - QUX_MAIL_USER=mon@mon.local
      - QUX_MONGO_CONNECTION_STRING=mongodb://quant-ux-mongo:27017
      - QUX_MONGO_DB_NAME=quantux
      - QUX_MONGO_TABLE_PREFIX=quantux
      - TZ=America/New_york
    depends_on:
      - mongo
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

**Comment by asitemade4u** [comment]
Hi Klaus,
I do not understand: the `container_name` instruction was indeed input in my `docker-compose` file: `qux`
This is how I define the stacks: the main container has a short name, others are derived from it.
Here: `qux` then `qux-mgo`, `qux-frt`
We have 40+ stacks here so I guess that rule is not so bad ;o))

**Comment by KlausSchaefers** [comment]
If you want to stay with the short name, change the `QUX_PROXY_UR` env variable in the front-end. The front-end will setup a proxy that redirects all request to that url.  When running in docker, the host name will be resolved to the container name, if there is one with the same name.

```
 - QUX_PROXY_URL=http://<your-container-name>:8080
```

**Comment by asitemade4u** [comment]
I tried but it did not change anything.

**Comment by asitemade4u** [comment]
I also change the line `- QUX_HTTP_HOST=http://qux:8082`
Same issue.

**Comment by KlausSchaefers** [comment]
Can you try the following compose locally? This works for me.

```
version: '3'

services:
  mongo:
    restart: always
    container_name: quant-ux-mongo
    image: mongo
    volumes:
      - ./data:/data/db        # pth for the data to be stored and kept on your host machine is on the left side of the ":"
  qux-fe:
    restart: always
    container_name: quant-ux-frontend
    image: klausenschaefersinho/quant-ux
    environment:
      - QUX_PROXY_URL=http://quant-ux-backend:8080        # this is the path the front end uses to talk tot he backend
      - QUX_AUTH=qux
      - QUX_KEYCLOAK_REALM=qux
      - QUX_KEYCLOAK_CLIENT=qux
      - QUX_KEYCLOAK_URL=http://keycloak:8180
      - QUX_WS_URL=
    links:
      - mongo
      - qux-be
    ports:
      - 8082:8082        # change the left side port if your host machine already has 8082 in use
    depends_on:
      - qux-be
  qux-be:
    restart: always
    container_name: quant-ux-backend
    image: klausenschaefersinho/quant-ux-backend
    environment:
      - QUX_HTTP_HOST=http://quant-ux-frontend:8082        # this is the path the backend uses to talk to the front end
      - QUX_HTTP_PORT=8080        # This is the port the backend will use
      - QUX_MONGO_DB_NAME=quantux        # the database / collection name in mongodb
      - QUX_MONGO_TABLE_PREFIX=quantux        # table / document prefix in mongodb
      - QUX_MONGO_CONNECTION_STRING=mongodb://quant-ux-mongo:27017        # this assumes your mongodb container will be called "quant-ux-mongo" in the docker-compose file
      - QUX_MAIL_USER=mail_admin@example.com        # this should be your smtp email user
      - QUX_MAIL_PASSWORD=sTr0ngPa55w0Rd        # this should be your smtp email password
      - QUX_MAIL_HOST=mail.example.com        # this should be your smtp host address
      - QUX_JWT_PASSWORD=some-long-string-of-mix-case-chars-and-nums        # you should change this to a real JWT secret
      - QUX_IMAGE_FOLDER_USER=/qux-images        # just a folder name, change if you like
      - QUX_IMAGE_FOLDER_APPS=/qux-image-apps        # just a folder name, change if you like
      - TZ=America/Chicago        # change to your timezone
      - QUX_AUTH_SERVICE=keycloak
      - QUX_KEYCLOAK_SERVER=http://keycloak:8180 # just the keycloak host & port
      - QUX_KEYCLOAK_REALM=barista
    depends_on:
      - mongo
```
